FROM registry.access.redhat.com/ubi8/ubi:8.4

# Generic labels
LABEL Component="httpd" \
      Name="s2i-do288-httpd" \
      Version="1.0" \
      Release="1"

# Labels consumed by RHOCP

# This label is used to categorize this image as a builder image in the
# RHOCP web console.

# Apache HTTP Server DocRoot
ENV DOCROOT /var/www/html

RUN   yum install -y --nodocs --disableplugin=subscription-manager httpd && \
      yum clean all --disableplugin=subscription-manager -y && \
      echo "This is the default index page from the s2i-do288-httpd S2I builder image." > ${DOCROOT}/index.html

# Change web server port to 8080

# Copy the S2I scripts to the default location indicated by the
# io.openshift.s2i.scripts-url LABEL (default is /usr/libexec/s2i)
